// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.AdopterPetGenderPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdopterId")
                        .HasColumnType("UUID")
                        .HasColumnName("adopter_id");

                    b.Property<Guid>("PetGenderId")
                        .HasColumnType("UUID")
                        .HasColumnName("gender_id");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("PetGenderId");

                    b.ToTable("adopter_pet_gender_preferences", (string)null);
                });

            modelBuilder.Entity("Domain.AdopterPetSizePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdopterId")
                        .HasColumnType("UUID")
                        .HasColumnName("adopter_id");

                    b.Property<Guid>("PetSizeId")
                        .HasColumnType("UUID")
                        .HasColumnName("size_id");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("PetSizeId");

                    b.ToTable("adopter_pet_size_preferences", (string)null);
                });

            modelBuilder.Entity("Domain.AdopterPetTypePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdopterId")
                        .HasColumnType("UUID")
                        .HasColumnName("adopter_id");

                    b.Property<Guid>("PetTypeId")
                        .HasColumnType("UUID")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("adopter_pet_type_preferences", (string)null);
                });

            modelBuilder.Entity("Domain.Adoption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdopterId")
                        .HasColumnType("UUID")
                        .HasColumnName("adopter_id");

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("DATE")
                        .HasColumnName("adoption_date");

                    b.Property<int>("Approved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved");

                    b.Property<string>("CounselorNotes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("counselor_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("DATE")
                        .HasColumnName("follow_up_date");

                    b.Property<Guid>("PetId")
                        .HasColumnType("UUID")
                        .HasColumnName("pet_id");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("PetId");

                    b.ToTable("adoptions", (string)null);
                });

            modelBuilder.Entity("Domain.AdoptionStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("adoption_statuses", (string)null);
                });

            modelBuilder.Entity("Domain.HealthStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("health_statuses", (string)null);
                });

            modelBuilder.Entity("Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.MedicalCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_name");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("UUID")
                        .HasColumnName("medical_record_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("medical_conditions", (string)null);
                });

            modelBuilder.Entity("Domain.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("LastMedicalCheckup")
                        .HasColumnType("DATE")
                        .HasColumnName("last_medical_checkup");

                    b.Property<string>("MicrochipNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("microchip_number");

                    b.Property<bool>("SpayNeuterStatus")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("spay_neuter_status");

                    b.Property<Guid>("VetId")
                        .HasColumnType("UUID")
                        .HasColumnName("veterinarian_id");

                    b.HasKey("Id");

                    b.HasIndex("VetId");

                    b.ToTable("medical_records", (string)null);
                });

            modelBuilder.Entity("Domain.OwnerPetListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdopterId")
                        .HasColumnType("UUID")
                        .HasColumnName("adopter_id");

                    b.Property<float>("AdoptionFee")
                        .HasColumnType("DECIMAL")
                        .HasColumnName("adoption_fee");

                    b.Property<Guid>("PetId")
                        .HasColumnType("UUID")
                        .HasColumnName("pet_id");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("review_date");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("submission_date");

                    b.Property<Guid>("SurrenderReasonId")
                        .HasColumnType("UUID")
                        .HasColumnName("surrender_reason_id");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("PetId");

                    b.HasIndex("SurrenderReasonId");

                    b.ToTable("owner_pet_listings", (string)null);
                });

            modelBuilder.Entity("Domain.OwnerPetListingDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_type");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_url");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("UUID")
                        .HasColumnName("listing_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("owner_pet_listing_documents", (string)null);
                });

            modelBuilder.Entity("Domain.OwnerSurrenderReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("owner_surrender_reasons", (string)null);
                });

            modelBuilder.Entity("Domain.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdoptionStatusId")
                        .HasColumnType("UUID")
                        .HasColumnName("adoption_status_id");

                    b.Property<int>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("age_years");

                    b.Property<string>("AvatarImg")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_img");

                    b.Property<string>("BehaviorialNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("behaviorial_notes");

                    b.Property<string>("Breed")
                        .HasColumnType("TEXT")
                        .HasColumnName("breed");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("energy_level");

                    b.Property<bool>("GoodWithCats")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("good_with_cats");

                    b.Property<bool>("GoodWithChildren")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("good_with_children");

                    b.Property<bool>("GoodWithDogs")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("good_with_dogs");

                    b.Property<Guid>("HealthStatusId")
                        .HasColumnType("UUID")
                        .HasColumnName("health_status_id");

                    b.PrimitiveCollection<string[]>("ImageShowcase")
                        .IsRequired()
                        .HasColumnType("TEXT[]")
                        .HasColumnName("image_showcase");

                    b.Property<DateTime?>("IntakeDate")
                        .HasColumnType("DATE")
                        .HasColumnName("intake_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("PetGenderId")
                        .HasColumnType("UUID")
                        .HasColumnName("gender_id");

                    b.Property<Guid>("PetSizeId")
                        .HasColumnType("UUID")
                        .HasColumnName("size_id");

                    b.Property<Guid>("PetTypeId")
                        .HasColumnType("UUID")
                        .HasColumnName("type_id");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("TEXT")
                        .HasColumnName("special_requirements");

                    b.HasKey("Id");

                    b.HasIndex("AdoptionStatusId");

                    b.HasIndex("HealthStatusId");

                    b.HasIndex("PetGenderId");

                    b.HasIndex("PetSizeId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("Domain.PetGender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("pet_genders", (string)null);
                });

            modelBuilder.Entity("Domain.PetSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("pet_sizes", (string)null);
                });

            modelBuilder.Entity("Domain.PetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("pet_types", (string)null);
                });

            modelBuilder.Entity("Domain.ShelterPetListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AdoptionFee")
                        .HasColumnType("DECIMAL")
                        .HasColumnName("adoption_fee");

                    b.Property<DateOnly?>("IntakeDate")
                        .HasColumnType("DATE")
                        .HasColumnName("intake_date");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("UUID")
                        .HasColumnName("medical_record_id");

                    b.Property<Guid>("PetId")
                        .HasColumnType("UUID")
                        .HasColumnName("pet_id");

                    b.Property<Guid>("ShelterId")
                        .HasColumnType("UUID")
                        .HasColumnName("shelter_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PetId");

                    b.HasIndex("ShelterId");

                    b.ToTable("shelter_pet_listings", (string)null);
                });

            modelBuilder.Entity("Domain.Vaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("UUID")
                        .HasColumnName("medical_record_id");

                    b.Property<DateOnly>("VaccineDate")
                        .HasColumnType("Date")
                        .HasColumnName("vaccine_date");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vaccine_name");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("vaccinations", (string)null);
                });

            modelBuilder.Entity("Domain.Veterinarian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("veterinarians", (string)null);
                });

            modelBuilder.Entity("Domain.VeterinarianSpecilization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("specialization");

                    b.Property<Guid>("VeterinarianId")
                        .HasColumnType("UUID")
                        .HasColumnName("vet_id");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("vet_specializations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Shelter", b =>
                {
                    b.HasBaseType("Domain.Identity.ApplicationUser");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT")
                        .HasColumnName("website");

                    b.Property<bool>("isNoKill")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("is_no_kill");

                    b.ToTable("shelters", (string)null);
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.HasBaseType("Domain.Identity.ApplicationUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("has_children");

                    b.Property<bool>("HasOtherPets")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("has_other_pets");

                    b.Property<string>("HomeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("home_type");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.AdopterPetGenderPreference", b =>
                {
                    b.HasOne("Domain.User", "Adopter")
                        .WithMany("AdopterPetGenderPreferences")
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PetGender", "PetGender")
                        .WithMany()
                        .HasForeignKey("PetGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("PetGender");
                });

            modelBuilder.Entity("Domain.AdopterPetSizePreference", b =>
                {
                    b.HasOne("Domain.User", "Adopter")
                        .WithMany("AdopterPetSizePreferences")
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PetSize", "PetSize")
                        .WithMany()
                        .HasForeignKey("PetSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("PetSize");
                });

            modelBuilder.Entity("Domain.AdopterPetTypePreference", b =>
                {
                    b.HasOne("Domain.User", "Adopter")
                        .WithMany("AdopterPetTypePreferences")
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PetType", "PetType")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("PetType");
                });

            modelBuilder.Entity("Domain.Adoption", b =>
                {
                    b.HasOne("Domain.User", "Adopter")
                        .WithMany()
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Domain.MedicalCondition", b =>
                {
                    b.HasOne("Domain.MedicalRecord", null)
                        .WithMany("MedicalConditions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MedicalRecord", b =>
                {
                    b.HasOne("Domain.Veterinarian", "Veterinarian")
                        .WithMany()
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Domain.OwnerPetListing", b =>
                {
                    b.HasOne("Domain.User", "Adopter")
                        .WithMany()
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.OwnerSurrenderReason", "SurrenderReason")
                        .WithMany()
                        .HasForeignKey("SurrenderReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("Pet");

                    b.Navigation("SurrenderReason");
                });

            modelBuilder.Entity("Domain.OwnerPetListingDocument", b =>
                {
                    b.HasOne("Domain.OwnerPetListing", "Listing")
                        .WithMany("OwnerPetListingDocuments")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Domain.Pet", b =>
                {
                    b.HasOne("Domain.AdoptionStatus", "AdoptionStatus")
                        .WithMany()
                        .HasForeignKey("AdoptionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.HealthStatus", "HealthStatus")
                        .WithMany()
                        .HasForeignKey("HealthStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PetGender", "PetGender")
                        .WithMany()
                        .HasForeignKey("PetGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PetSize", "PetSize")
                        .WithMany()
                        .HasForeignKey("PetSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.PetType", "PetType")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdoptionStatus");

                    b.Navigation("HealthStatus");

                    b.Navigation("PetGender");

                    b.Navigation("PetSize");

                    b.Navigation("PetType");
                });

            modelBuilder.Entity("Domain.ShelterPetListing", b =>
                {
                    b.HasOne("Domain.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Shelter", "Shelter")
                        .WithMany()
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("Pet");

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("Domain.Vaccination", b =>
                {
                    b.HasOne("Domain.MedicalRecord", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.VeterinarianSpecilization", b =>
                {
                    b.HasOne("Domain.Veterinarian", null)
                        .WithMany("VetSpecializations")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Shelter", b =>
                {
                    b.HasOne("Domain.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Domain.Shelter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.HasOne("Domain.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Domain.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MedicalRecord", b =>
                {
                    b.Navigation("MedicalConditions");

                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Domain.OwnerPetListing", b =>
                {
                    b.Navigation("OwnerPetListingDocuments");
                });

            modelBuilder.Entity("Domain.Veterinarian", b =>
                {
                    b.Navigation("VetSpecializations");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("AdopterPetGenderPreferences");

                    b.Navigation("AdopterPetSizePreferences");

                    b.Navigation("AdopterPetTypePreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
