version: "3"
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pawprint-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pawprint

networks:
  pawprint-network:
    driver: bridge
volumes:
  postgres-data:
